// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4hQ7rlAbPyJWyLgWMVkRu6OS-fQzYJ4w',
    appId: '1:810957053802:web:bf981bbfc943e0f7044f13',
    messagingSenderId: '810957053802',
    projectId: 'fir-app-73ede',
    authDomain: 'fir-app-73ede.firebaseapp.com',
    storageBucket: 'fir-app-73ede.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcDYfKMsd_bQ8k_85Ee8mSuLE5LfwhP_A',
    appId: '1:810957053802:android:52420fb6e56baae5044f13',
    messagingSenderId: '810957053802',
    projectId: 'fir-app-73ede',
    storageBucket: 'fir-app-73ede.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRw-KuHX5yE_b8nE7pFM8311joMo4_uTc',
    appId: '1:810957053802:ios:4a9551c095821335044f13',
    messagingSenderId: '810957053802',
    projectId: 'fir-app-73ede',
    storageBucket: 'fir-app-73ede.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
